version: 2

models:
  - name: gold_customer_metrics
    description: Customer-level business metrics and segmentation for analytics and reporting
    columns:
      - name: customer_id
        description: Unique customer identifier
        tests:
          - unique
          - not_null
      - name: email
        description: Customer email address
        tests:
          - not_null
      - name: full_name
        description: Customer full name
        tests:
          - not_null
      - name: customer_since
        description: Date when customer record was created
      - name: total_orders
        description: Total number of orders placed by customer
        tests:
          - not_null
      - name: delivered_orders
        description: Number of successfully delivered orders
        tests:
          - not_null
      - name: cancelled_orders
        description: Number of cancelled orders
        tests:
          - not_null
      - name: lifetime_value
        description: Total revenue generated by customer (sum of all orders)
        tests:
          - not_null
      - name: avg_order_value
        description: Average order amount for this customer
        tests:
          - not_null
      - name: first_order_date
        description: Date of customer's first order
      - name: last_order_date
        description: Timestamp of customer's most recent order
      - name: last_order_date_only
        description: Date of customer's most recent order (date only)
      - name: customer_segment
        description: Customer segmentation based on order count
        tests:
          - not_null
          - accepted_values:
              values: ['Never Ordered', 'One-Time Customer', 'Repeat Customer', 'VIP Customer']
      - name: customer_status
        description: Customer activity status based on recency
        tests:
          - not_null
          - accepted_values:
              values: ['Active', 'At Risk', 'Churned', 'Never Ordered']
      - name: dbt_loaded_at
        description: Timestamp when record was loaded by dbt

  - name: gold_daily_sales
    description: Daily aggregated sales metrics with moving averages for time-series analysis
    columns:
      - name: sales_date
        description: Date of the sales transactions
        tests:
          - unique
          - not_null
      - name: total_orders
        description: Total number of orders placed on this date
        tests:
          - not_null
      - name: unique_customers
        description: Number of unique customers who placed orders
        tests:
          - not_null
      - name: total_revenue
        description: Total revenue for the date
        tests:
          - not_null
      - name: avg_order_value
        description: Average order value for the date
        tests:
          - not_null
      - name: min_order_value
        description: Minimum order value for the date
      - name: max_order_value
        description: Maximum order value for the date
      - name: pending_orders
        description: Number of orders in pending status
        tests:
          - not_null
      - name: processing_orders
        description: Number of orders in processing status
        tests:
          - not_null
      - name: shipped_orders
        description: Number of orders in shipped status
        tests:
          - not_null
      - name: delivered_orders
        description: Number of orders in delivered status
        tests:
          - not_null
      - name: cancelled_orders
        description: Number of orders in cancelled status
        tests:
          - not_null
      - name: delivered_revenue
        description: Revenue from delivered orders
        tests:
          - not_null
      - name: cancelled_revenue
        description: Revenue from cancelled orders
        tests:
          - not_null
      - name: revenue_7day_ma
        description: 7-day moving average of revenue
      - name: revenue_30day_ma
        description: 30-day moving average of revenue
      - name: day_of_week
        description: Day of the week name (e.g., Monday, Tuesday)
      - name: day_of_week_num
        description: Day of the week as number (0=Sunday, 6=Saturday)
      - name: dbt_loaded_at
        description: Timestamp when record was loaded by dbt
