madt8102_dbt:
  target: dev
  outputs:
    dev:
      type: duckdb
      schema: public
      path: '/content/duckdb.duckdb'
      extensions:
        - httpfs
        - parquet
    
    prod:
      type: bigquery
      method: service-account
      project: madt-8102-479812
      dataset: main
      threads: 4
      keyfile: /Users/sirawich/Desktop/madt-8102-dbt-bq-key.json  # Replace with path to your keyfile
      location: US  # Replace with your GCP location (e.g., US, EU, asia-southeast1)
      timeout_seconds: 300
      retries: 1
