version: 2

models:
  - name: silver_customers
    description: Cleaned and standardized customer data with data quality rules applied
    columns:
      - name: customer_id
        description: Unique customer identifier
        tests:
          - unique
          - not_null
      - name: email
        description: Customer email address (standardized to lowercase)
        tests:
          - not_null
          - unique
      - name: first_name
        description: Customer first name (trimmed)
        tests:
          - not_null
      - name: last_name
        description: Customer last name (trimmed)
        tests:
          - not_null
      - name: full_name
        description: Customer full name (first + last)
        tests:
          - not_null
      - name: created_at
        description: Timestamp when customer record was created
      - name: updated_at
        description: Timestamp when customer record was last updated
      - name: dbt_loaded_at
        description: Timestamp when record was loaded by dbt

  - name: silver_orders
    description: Cleaned and standardized order data with customer validation
    columns:
      - name: order_id
        description: Unique order identifier
        tests:
          - unique
          - not_null
      - name: customer_id
        description: Foreign key to customer
        tests:
          - not_null
          - relationships:
              to: ref('silver_customers')
              field: customer_id
      - name: order_date
        description: Timestamp when order was placed
        tests:
          - not_null
      - name: order_date_only
        description: Date portion of order_date
        tests:
          - not_null
      - name: amount
        description: Order amount in dollars (must be positive)
        tests:
          - not_null
      - name: status
        description: Current order status (standardized to uppercase)
        tests:
          - not_null
          - accepted_values:
              values: ['PENDING', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED']
      - name: created_at
        description: Timestamp when order record was created
      - name: updated_at
        description: Timestamp when order record was last updated
      - name: dbt_loaded_at
        description: Timestamp when record was loaded by dbt
